# Criando o Docker-Compose de uma aplicação Web

version: "3.8"
services:
  http:
    image: nginx:stable-alpine3.17-slim
    ports:
      - 8085:80
      - 8443:443

  front-end:
    build:
      context: ./front-end/
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - ./front-end:/app
    ports:
      - 3000:3000